esphome:
  name: "${node_name}"
  build_path: "../../build/${node_name}"

logger:
  level: "${log_level}"

api:
  password: !secret "api_key"
  port: 6053  # Default
  reboot_timeout: "30min"

captive_portal: {}

ota:
  password: !secret "ota_password"
  safe_mode: true

wifi:
  ssid: !secret "wifi_ssid"
  password: !secret "wifi_password"
  fast_connect: true
  ap:
    ssid: "${node_name} Fallback"
    password: !secret "fallback_hotspot_password"

binary_sensor:
  - platform: "status"
    name: "${display_name} status"

sensor:
  - platform: "uptime"
    name: "${display_name} uptime"
    update_interval: "30min"
    unit_of_measurement: "h"
    filters:
      - lambda: "return int((x + 1800.0) / 3600.0);"
  - platform: "wifi_signal"
    name: "${display_name} WiFi signal"
    update_interval: "5min"

text_sensor:
  - platform: "version"
    name: "${display_name} ESPHome version"
  - platform: "wifi_info"
    ip_address:
      name: "${display_name} IP"
    ssid:
      name: "${display_name} SSID"
    bssid:
      name: "${display_name} BSSID"

switch:
  - platform: "restart"
    name: "${display_name} restart"

# Sync time with Home Assistant.
# time:
#   - platform: "homeassistant"
#     id: "homeassistant_time"
