esphome:
  name: "${node_name}"
  name_add_mac_suffix: false
  build_path: "../../../build/${node_name}"

logger:
  level: "${log_level}"

api:
  password: "${api_key}"
  port: 6053  # Default
  reboot_timeout: "30min"
  encryption:
    key: "${api_encryption_key}"

ota:
  password: "${ota_password}"
  safe_mode: true

binary_sensor:
  - platform: "status"
    name: "${display_name} status"

sensor:
  - platform: "uptime"
    name: "${display_name} uptime"
    update_interval: "30min"
    unit_of_measurement: "h"
    filters:
      - lambda: "return int((x + 1800.0) / 3600.0);"

text_sensor:
  - platform: "version"
    name: "${display_name} ESPHome version"

button:
  - platform: "restart"
    name: "Restart ${display_name}"
    entity_category: "diagnostic"
  - platform: "safe_mode"
    name: "Restart ${display_name} (safe mode)"
    entity_category: "diagnostic"

time:
  - platform: "homeassistant"
    id: "homeassistant_time"
