captive_portal: {}

wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  fast_connect: true
  ap:
    ssid: "${node_name} Fallback"
    password: "${wifi_fallback_hotspot_password}"

sensor:
  - platform: "wifi_signal"
    name: "WiFi signal"
    update_interval: "5min"

text_sensor:
  - platform: "wifi_info"
    ip_address:
      name: "IP"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"
