captive_portal: {}

wifi:
  ssid: !secret "wifi_ssid"
  password: !secret "wifi_password"
  fast_connect: true
  ap:
    ssid: "${node_name} Fallback"
    password: !secret "fallback_hotspot_password"
