i2c:
  - sda: "D2"
    scl: "D1"

dallas:
  - pin: "D5"

sensor:
  - platform: "am2320"
    humidity:
      name: "${display_name} humidity"
    temperature:
      name: "${display_name} temperature"
  - platform: "dallas"
    name: "${display_name} basking temperature"
    address: "${basking_temperature_address}"
    resolution: 12
