i2c:
  - sda: "D2"
    scl: "D1"

one_wire:
  - platform: "gpio"
    pin: "D5"

sensor:
  - platform: "am2320"
    humidity:
      name: "Hhumidity"
    temperature:
      name: "Temperature"
  - platform: "dallas_temp"
    name: "Basking temperature"
    address: "${basking_temperature_address}"
    resolution: 12
