external_components:
  - source: "github://geoffdavis/esphome-mitsubishiheatpump@2.5.0"
    components:
      - "mitsubishi_heatpump"

climate:
  - platform: "mitsubishi_heatpump"
    id: "heat_pump"
    name: "${display_name}"
    hardware_uart: "${uart_id}"
    remote_temperature_operating_timeout_minutes: 30
    remote_temperature_idle_timeout_minutes: 90
    horizontal_vane_select:
      name: "Horizontal Vane"
    vertical_vane_select:
      name: "Vertical Vane"
    supports:
      mode: ["HEAT_COOL", "COOL", "HEAT", "DRY", "FAN_ONLY"]
      fan_mode: ["AUTO", "DIFFUSE", "LOW", "MEDIUM", "MIDDLE", "HIGH"]
      swing_mode: ["OFF", "VERTICAL"]
    visual:
      min_temperature: 16
      max_temperature: 31
      temperature_step: 1.0

api:
  services:
    - service: "set_remote_temperature"
      variables:
        temperature: "float"
      then:
        - lambda: "id(heat_pump).set_remote_temperature(temperature);"

    - service: "use_internal_temperature"
      then:
        - lambda: "id(heat_pump).set_remote_temperature(0);"
