substitutions:
  node_name: "ground_floor_heat_pump"
  display_name: "Heat pump"
  log_level: "DEBUG"

  uart_id: "UART0"

esphome:
  platform: "ESP8266"
  board: "d1_mini"

logger:
  baud_rate: 0

packages:
  base_device: !include "../packages/common/base_device.yaml"
  wifi: !include "../packages/common/wifi.yaml"
  heatpump: !include "../packages/heatpump/mitsubishi_mszfe12na8.yaml"
