substitutions:
  display_name: "Heat pump"
  node_name: "ground_floor_heat_pump"

esphome:
  board: "d1_mini"
  platform: "ESP8266"

logger:
  baud_rate: 0

packages:
  base_device: !include
    file: "../packages/common/base_device.yaml"
    vars:
      log_level: "DEBUG"
      api_key: !secret "api_key"
      api_encryption_key: !secret "api_encryption_key"
      ota_password: !secret "ota_password"

  wifi: !include
    file: "../packages/common/wifi.yaml"
    vars:
      wifi_ssid: !secret "wifi_ssid"
      wifi_password: !secret "wifi_password"
      wifi_fallback_hotspot_password: !secret "wifi_fallback_hotspot_password"

  heatpump: !include
    file: "../packages/heatpump/mitsubishi_mszfe12na8.yaml"
    vars:
      uart_id: "UART0"
