name: "Validate"

"on": ["push"]

jobs:
  check:
    name: "Static check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Lint"
        run: "make lint"

  prepare:
    name: "Prepare environment"
    runs-on: "ubuntu-latest"
    outputs:
      devices: "${{ steps.data.outputs.devices }}"
      python_version: "${{ steps.data.outputs.python_version }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "List devices"
        id: "data"
        run: |
          devices_json=$(ls ./config/devices/ | jq -R -s -c 'split("\n")[:-1]')
          python_version="$(grep -v '#' .tool-versions | grep python | awk '{print $2}')"
          echo "devices=$devices_json" >> $GITHUB_OUTPUT
          echo "python_version=$python_version" >> $GITHUB_OUTPUT

  compile:
    name: "Compile ${{ matrix.device }}"
    runs-on: "ubuntu-latest"
    needs: "prepare"
    strategy:
      fail-fast: true
      matrix:
        device: "${{ fromJSON(needs.prepare.outputs.devices) }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ needs.prepare.outputs.python_version }}"
          cache: "pip"

      - name: "Install python dependencies"
        run: "pip install -r requirements.txt"

      - name: "Compile"
        run: |
          device_path=$(realpath "./config/devices/${{ matrix.device }}")

          cp -f "$device_path/.secrets.blank.yaml" "$device_path/secrets.yaml"
          python -m esphome compile "$device_path/main.yaml"
